config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-events'
  devise_for :users
  resources :sales
  resources :products

  get '/buy/:permalink', to: 'transactions#new', as: :show_buy
  post '/buy/:permalink', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download
  get '/iframe/:permalink', to: 'transactions#iframe', as: :buy_iframe

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  has_attached_file :file
  validates_attachment_content_type :file, content_type: [
    "image/jpg",
    "image/jpeg",
    "image/png",
    "image/gif",
    "application/pdf",
    "application/zip"
  ]

  has_many :sales
  validates :price, numericality: { greater_than: 0.49,
                                   message: "must be at least 50 cents" }
                                   
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  before_create :populate_guid
  validates :guid, uniqueness: true
  has_paper_trail

  include AASM

  aasm column: 'state' do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end

  end

  private

  def populate_guid
    if new_record?
      while !valid? || self.guid.nil?
        self.guid = SecureRandom.random_number(1_000_000_000).to_s(36)
      end
    end
  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: 'usd',
        description: self.email,
        source: self.stripe_token
      )
      balance = Stripe::BalanceTransaction.retrieve(charge.balance_transaction)
      self.update(
        stripe_id: charge.id,
        card_expiration: Date.new(charge.source.exp_year, charge.source.exp_month, 1),
        fee_amount: balance.fee
      )
      self.finish!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.save
    respond_with(@product)
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :permalink, :description, :price, :file)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:email, :guid, :product_id, :stripe_id)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :strip_iframe_protection

  def new
    @product = Product.find_by!(permalink: params[:permalink])
  end

  def create
    @product = Product.find_by!(permalink: params[:permalink])

    sale = @product.sales.create(
      amount: @product.price,
      email: params[:email],
      stripe_token: params[:stripeToken]
    )
    sale.process!
    if sale.finished?
      redirect_to pickup_url(guid: sale.guid)
    else
      flash.now[:alert] = sale.error
      render :new
    end
  end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @product = @sale.product
  end

  def download
    @sale = Sale.find_by!(guid: params[:guid])
    resp = HTTParty.get(@sale.product.file.url)
    url = @sale.product.file.url
    send_data resp.body,
      filename: File.basename(url),
      content_type: resp.headers['Content-Type']
  end

  def iframe
    @product = Product.find_by!(permalink: params[:permalink])
    @sale = Sale.new(product_id: @product)
  end

  private

  def strip_iframe_protection
    response.headers.delete('X-Frame-Options')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_price(amount)
    sprintf("$%0.2f", amount/100)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stripe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
    $(function(){
      Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
      $('#payment-form').submit(function(event) {
        var $form = $(this);
        $form.find('button').prop('disabled', true);
        Stripe.card.createToken({
          number: $('#number').val(),
          cvc: $('#cvc').val(),
          exp_month: $('#exp-month').val(),
          exp_year: $('#exp-year').val()
        }, stripeResponseHandler);
        return false;
      });
      function stripeResponseHandler(status, response) {
        var $form = $('#payment-form');
        if (response.error) {
          $form.find('.payment-errors').text(response.error.message);
          $form.find('button').prop('disabled', false);
        } else {
          var token = response.id;
          $form.append($('<input type="hidden" name="stripeToken"/>').val(token));
          $form.get(0).submit();
        }
      }
    });
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, msg| %>
    <%= content_tag :p, msg, class: type %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br>
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Permalink</th>
      <th>Description</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.permalink %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.user %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @product.permalink %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sales/_form.html.erb
<div class="well">
  <%= form_for(@sale) do |f| %>
    <% if @sale.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

        <ul>
        <% @sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :guid %><br>
      <%= f.text_field :guid %>
    </div>
    <div class="field">
      <%= f.label :product_id %><br>
      <%= f.text_field :product_id %>
    </div>
    <div class="field">
      <%= f.label :stripe_id %><br>
      <%= f.text_field :stripe_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Guid</th>
      <th>Product</th>
      <th>Stripe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.email %></td>
        <td><%= sale.guid %></td>
        <td><%= sale.product %></td>
        <td><%= sale.stripe_id %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>


<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
  </tr>
  <% @sale.attributes.sort.each do |key, value| %>
  <tr>
    <td><%= key %></td>
    <td><%= value %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Stripe', "https://manage.stripe.com/payments/#{@sale.stripe_id}" %>
<%= link_to 'Back', sales_path %>


<table>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Event</th>
      <th>Changes</th>
    </tr>
  </thead>
  <tbody>
  <% @sale.versions.each do |version| %>
    <tr>
      <td><%= version.created_at %></td>
      <td><%= version.event %></td>
      <td>
        <% version.changeset.sort.each do |key, value| %>
          <b><%= key %></b>: <%= value[0] %> to <%= value[1] %><br>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/transactions/_form.html.erb
<%= form_tag buy_path(permalink: permalink), :class => '', :id => 'payment-form' do %>
  <div class="row">
  </div>
  <div class="row">
    <div style="position: absolute; left: 20px">
      <label class="control-label" for="email">Email</label>
      <input type="email" name="email" id="email" placeholder="you@example.com"/>
    </div>
    <div style="position: absolute; left: 270px">
      <label class="control-label" for="number">Card Number</label>
      <input type="text" size="20" data-stripe="number" id="number" placeholder="**** **** **** ****" pattern="[\d ]*" style="width: 16em"/>
    </div>
  </div>
  <div class="row" style="margin-top: 65px">
    <div style="position: absolute; left: 20px">
      <label class="control-label" for="cvc">CVC</label>
      <input type="text" style="width: 3em" size="3" data-stripe="cvc" id="cvc" placeholder="***" pattern="\d*"/>
      <%= image_tag "visa.png", class: "card-image" %>
    </div>
    <div style="position: absolute; left: 150px">
      <label class="control-label">Exp (MM/YYYY)</label>
      <input style="width: 2em" type="text" size="2" id="exp-month" data-stripe="exp-month" placeholder="MM" pattern="\d*"/>
      <span> / </span>
      <input style="width: 3em" type="text" size="4" id="exp-year" data-stripe="exp-year" placeholder="YYYY" pattern="\d*"/>
    </div>
  </div>
  <div class="row" style="margin-top: 70px">
    <div class="price" >Price: <%= price %></div>
    <div style="position: absolute; left: 400px">
      <button type="submit" class="btn btn-primary btn-large">Buy Now</button>
    </div>
  </div>
<% end %>

app/views/transactions/iframe.html.erb
<h1><%= @product.name %></h1>

<p>Price: <%= formatted_price(@product.price) %></p>

<%= render 'form', permalink: @product.permalink, sale: @sale, price: formatted_price(@product.price) %>

app/views/transactions/new.html.erb
<h1><%= @product.name %></h1>
<%= @product.description %>
<% if @error %>
  <%= @error %>
<% end %>

<button class="btn btn-primary" id="openBtn">Buy</button>
<div id="paymentModal" class="modal hide fade" role="dialog">
  <div class="modal-body">
    <iframe src="" style="zoom:0.5" width="100%" height="550" frameborder="0">

    </iframe>
  </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script type="text/javascript">
  var frameSrc = "/iframe/<%= @product.permalink %>"; // You'll want to customize this.
  $("#openBtn").click(function() {
    $("#paymentModal").on("show", function() {
      $('iframe').attr('src', frameSrc);
    });
    $("#paymentModal").modal({show: true});
  });
</script>

app/views/transactions/pickup.html.erb
<h1>Download <%= @product.name %></h1>
<p>Thanks for buying "<%= @product.name %>" You can download your purchase by clicking the link below.</p>
<p><%= link_to 'Download', download_url(guid: @sale.guid) %></p>